# Generated by Django 5.2 on 2025-06-19 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
