# Generated by Django 5.2 on 2025-06-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_customerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('avatar', models.CharField(blank=True, default='icons/default_avatar.png', max_length=100, verbose_name='頭像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '顧客資料',
                'verbose_name_plural': '顧客資料',
            },
        ),
    ]
