# Generated by Django 5.2 on 2025-06-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='使用者名稱')),
                ('avatar', models.CharField(default='icons/default_avatar.png', max_length=200, verbose_name='頭像路徑')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員列表',
            },
        ),
    ]
